[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GlobalTradeAnalysisProjectModelV7 = "17bf7c9d-bd82-4e09-a8b5-dac70c0d12c3"
HeaderArrayFile = "e2354eee-dcc0-4139-addc-ce07950641e0"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
